# Generated by Django 3.0.4 on 2020-03-25 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='add_product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(max_length=120)),
                ('Type', models.CharField(max_length=120)),
                ('Title', models.CharField(max_length=120)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=100)),
                ('Description', models.TextField()),
                ('Specification', models.TextField()),
                ('Sellit_assured', models.BooleanField()),
                ('Image', models.ImageField(blank=True, upload_to='images/')),
            ],
        ),
    ]
